name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [update]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check VISION secret
        run: |
          if [ -z "${{ secrets.VISION }}" ]; then
            echo "Error: VISION secret is not set"
            exit 1
          fi

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (AMD64)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            chb2024/pieces-os:${{ secrets.VISION }}
            chb2024/pieces-os:latest
          platforms: linux/amd64

      - name: Build and push Docker image (ARM64)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            chb2024/pieces-os-arm:${{ secrets.VISION }}
            chb2024/pieces-os-arm:latest
          platforms: linux/arm64

      - name: Notify on success
        run: echo "Docker image built and pushed successfully."
